[versions]
stonecutter = "0.9.8"
mod-publish = "2.2.1"
dotenv-gradle = "4.0.0"
loom-back-compat = "0.4.2"
neoforge-moddev = "2.0.148"
foojay = "1.0.0"
kotlin-jvm = "2.4.20"
vanniktech-maven-publish = "0.36.0"
serialization-json = "1.12.0-RC"
serialization-toml = "0.6.1"

[libraries]
mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish" }
kikugie-stonecutter = { module = "dev.kikugie:stonecutter", version.ref = "stonecutter" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }
vanniktech-maven-publish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktech-maven-publish" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
serialization-toml = { module = "dev.eav.tomlkt:tomlkt", version.ref = "serialization-toml" }

[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv-gradle" }
loom-back-compat = { id = "dev.kikugie.loom-back-compat", version.ref = "loom-back-compat" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
legacyforge-moddev = { id = "net.neoforged.moddev.legacyforge", version.ref = "neoforge-moddev" }
